## => Site Settings
##############################
text_skin: "dark" # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: "tomorrow-night" # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : https://alaiatai.github.io/oncodecoded/ # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : Cancer and You
subtitle: Understanding Genetic Mutations & Precision Medicine
description: > # this means to ignore newlines until "Language & timezone"
  A simple guide to cancer genomics and personalized medicine.
  Learn how genetic mutations shape treatment and impact prognosis.


## => Language and Timezone
##############################
lang: # the language of your site, default as "en"
timezone: AEDT # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : # "person" (default), "organization"
  name      : Alaia
  url       : https://alaiatai.github.io/oncodecoded/
  avatar    : # path or url of avatar image (square)
  email     : alaiaxtai@gmail.com
  linkedin  : "alaiatai" # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name


## => Paths
##############################
paths:
  home: /
  about: /about/
  archive: /archive.html
  rss: /feed.xml
  
## => Navigation (Optional: If you want a top menu)
##############################
menu:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Case Studies
    url: /case-studies/
  - title: Interactive Tools
    url: /interactive-tools/
  - title: Resources
    url: /resources/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/

## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: "google" # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : "G-1L6NGEE32Y" # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

collections:
  pages:
    output: true
    permalink: /:path/

include: ["_pages"]

header_pages:
  - index.md
  - about.md
  - resources.md
  - case-studies.md
  - interactive-tools.md
  - blog.md

